### ISSUE TITLE
Full-time or permanent employees?

### ISSUE THREAD

**Issue by philwills** [triketora/women-in-software-eng#283]
In the contributing doc, it states:

> Only full-timers please; no interns or contractors.

Does this actually mean full-timers, or does it mean 'permanent employees'? 

We have contractors who are full-time, but some of our most senior engineers are permanent employees who are a core part of our engineering team, but work four days a week, so wouldn't qualify as full-timers. It would feel very strange not to include them in our numbers.

**Comment by triketora** [comment]
Great question. I have to admit I am not super well-versed on the legal terminology so I had to do some light googling and from what I'm reading, I think what I mean is full-time permanent employees (the terminology is confusing -- I see a lot of "full-time vs. contract" and "employee vs. contractor"). The main thing is that there needs to be some distinguishing line and although it'll be fuzzy right around that line, the line still has to exist. I could probably buy an argument for 80%+ time, but it seems easier to draw the line at 100% time. What do you think?

**Comment by sallygoble** [comment]
Just chipping in - my feeling is that a disproportionate number of women engineers probably work part time (ie less than 100%) - because of childcare. As women are more likely to work part time than men generally speaking, having a line at 100%  probably skews data to exclude more women than men. (This is in fact not the fact at our company but I can see a situation where it might)
